# Generated by Django 3.0.3 on 2021-01-17 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomkeeper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Building'),
        ),
        migrations.AddField(
            model_name='room',
            name='equipments',
            field=models.ManyToManyField(through='reservations.EquipmentRoom', to='reservations.Equipment'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_keepers',
            field=models.ManyToManyField(through='reservations.RoomKeeper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='softwares',
            field=models.ManyToManyField(through='reservations.SoftwareRoom', to='reservations.Software'),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.RoomType'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.ReservationType'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentroom',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Room'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Building'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='coordinators',
            field=models.ManyToManyField(through='reservations.Coordinator', to=settings.AUTH_USER_MODEL),
        ),
    ]
